### ISSUE TITLE
Checkbox onChange is called when component is rendered first time with initialValue

### ISSUE THREAD

**Issue by sonugk** [galio-org/galio#133]
**Describe the bug**
Checkbox component's `onChange` handler is called when component is rendered for the first time with `initialValue`
In the Galio version before 0.6 it was not the case

**To Reproduce**
1. Add Galio Checkbox component in you screen
2. E.g. `<Checkbox onChange={() => {alert('OnChangeCalled')  this.setState({ termsAccepted: !this.state.termsAccepted })}} initialValue={this.state.termsAccepted} label="I agree with the Terms"     />`, termsAccepted  is boolean property
3. You can see alert message `OnChangeCalled` even when component is loaded for the first time

**Expected behavior**
When initialValue is set first time onChange handler should not be called

**Smartphone (please complete the following information):**
 - Samsung Galasy S8
 - Type of device: simulator
 - OS: Android 8
 - React-Native version: 0.6
 - Expo version:  34

**Comment by palingheorghe** [comment]
Hi @sonugk ! Sorry for taking so long to respond. I tested and you're right, the `onChange` function is getting called at the beginning because of the `useEffect` function. Basically every time the `checked` boolean state is changed the function is getting called, this happens at the first render of our component as well. We'll have to figure out a way for the Effect to not render at the beginning. 

🧜🏽‍♂️

**Comment by sonugk** [comment]
> Hi @sonugk ! Sorry for taking so long to respond. I tested and you're right, the `onChange` function is getting called at the beginning because of the `useEffect` function. Basically every time the `checked` boolean state is changed the function is getting called, this happens at the first render of our component as well. We'll have to figure out a way for the Effect to not render at the beginning.
> 
> 🧜🏽‍♂️

Thank you for the response. The current workaround I am using is `setTimeout` setting `termsAccepted` state field to `true` again in `componentWillMount`. I will wait for the solution.

**Comment by palingheorghe** [comment]
I think the best way of actually solving the problem would be by modifying the component back to a class based component. That way we can have more control over the lifecycle functions.

**Comment by nastarfan** [comment]
@palingheorghe any update on this? I'm experiencing this issue as well

**Comment by palingheorghe** [comment]
Hi @nastarfan ! We haven't yet modified this component but this will be surely done when we're realeasing v1.0

**Comment by AndyOsei** [comment]
@palingheorghe will open a PR to fix this...

**Comment by matthew-biggins** [comment]
Having this problem as well. I see the PR fix. Looking forward to that. I'm just adding my workaround for anyone else experiencing this until the fix is implemented. This allows me to use the Checkbox without it calling onChange when first rendered.

`const [testing, setTesting] = useState(0)`

`function someFunction() {
    if (testing != 0) {
      // function logic
    }
    setTesting(1);
}`

In function render:
`<Checkbox
            initialValue={props.value}
            onChange={someFunction}
  />`

**Comment by palingheorghe** [comment]
Closed because we've merged the PR into the `dev` branch. Thank you for all the help guys!
