### ISSUE TITLE
Can't change the color of a button on press

### ISSUE THREAD

**Issue by Danielgb23** [galio-org/galio#207]
I am trying to build a like button that changes color when you click it to mark the target as 'liked'. So I used this function called on the button:
function like_quote(_this) {
	_this.iconColor= theme.COLORS.THEME 
	Alert.alert('Like!')
}

 <Button
              onlyIcon
              icon="heart"
	      key="like"
              iconFamily="font-awesome"
              iconSize={theme.SIZES.BASE}
              iconColor={'#ffbbbb'}//theme.COLORS.THEME
              color="transparent"
              style={{ marginRight: theme.SIZES.BASE }}
              onPress={() => like_quote(this)}
            />,

But nothing happens, I have tried changing other button features options' but nohing happens either.

The button should change color as I change it's color variable.

Android 10 motorola expo version 2.15.4

**Comment by palingheorghe** [comment]
Hi @Danielgb23 
Thank you for this issue but this is not a problem with Galio. This has more to do with some basic principles of React and React-Native. `iconColor` is a prop of Button, and you can't access it via an external function. In order to change iconColor dynamically you'd have to say something like `iconColor={this.state.someVar}` and you should change the state via `this.setState();` function. You can find more about all of this here: https://reactjs.org/docs/state-and-lifecycle.html .

I'm going to close this issue as it has nothing to do with Galio.
