### ISSUE TITLE
Using Galio with ejected app

### ISSUE THREAD

**Issue by matthintosh** [galio-org/galio#68]
**Bug description**
Hello, I'm would like to use Galio component on an react-native ejected app.
Actually I have the issue which is : "The Expo SDK requires expo to run"

**To Reproduce**
Only trying to use Galio component on and ejected app

**Screenshots**
![simulator screen shot - iphone x - 2019-02-11 at 14 50 02](https://user-images.githubusercontent.com/6673744/52567416-907b5d80-2e0c-11e9-94ce-b01ec53896ae.png)

**Smartphone:**
 - Device: [iPhone X]
 - Type of device: [simulator]
 - OS: [ios 11.3]
 - React-Native version: [e.g. 0.57.8]
 - Expo version: ejected app (expoKit ?)

Thanks for your help !

**Comment by harshrajk** [comment]
I second this.I am still waiting eagerly to use this without expo.

**Comment by palingheorghe** [comment]
Hi, 

Galio has Expo as a dependency so it needs it in order to run. By removing Expo you leave no option for React-Native but to throw out that error.

If you must remove Expo I recommend doing the following. Clone the repo and copy the `src` folder inside a 'galio' folder in your app's root folder. Now... this isn't the best approach being the fact that the Icon and Button components have dependencies in Expo and you won't be able to use them. But this is the only workaround at the moment. 

We will most certainly create a better, well-rounded workaround Expo. It is on our to-do list. 

Thanks!

**Comment by matthintosh** [comment]
Hi @palingheorghe,

Thank you for your reply.
I will probably wait for the the updated version of Galio because I would like to use buttons...

Regards,

**Comment by hetmann** [comment]
Or refactoring all the components to be Expo free :)

**Comment by palingheorghe** [comment]
Hi @hetmann, 
As I said: 
> We will most certainly create a better, well-rounded workaround Expo. It is on our to-do list.
This is one of our goals.

I'll close this now because this question has been answered. 

Thanks,
❤️
