### ISSUE TITLE
github.com-galio-org-galio@examples

### ISSUE THREAD

**Issue by cooleyeglasses** [galio-org/galio#76]
**Describe the bug**
Unable to resolve module ‘module://galio-framework.js’

**To Reproduce**
1. Go to https://snack.expo.io/@cooleyeglass/github.com-galio-org-galio@examples
2. Click on 'Tap to Play' of the PREVIEW Android 
3. Scroll down to bottom of  browser
Device: (78:20)
Unable to resolve module ‘module://galio-framework.js’
Evaluating module://galio-framework.js
Evaluating module://src/screens/Article.js
Evaluating module://routes.js
Evaluating module://App.js
Loading module://App.js

**Expected behavior**

**Screenshots**
![udate](https://user-images.githubusercontent.com/45550571/55644964-ed423580-5809-11e9-9b14-c5914cc2e566.png)

**Smartphone (please complete the following information):**
 - Device: Android
 - Type of device: Simulator
 - OS: Android SDK built for x86
 - React-Native version:
 - Expo version: 29.0.0

**Additional context**

**Comment by palingheorghe** [comment]
Hi @cooleyeglasses ! 

I am not completely sure what's the problem here but I guess it has something to do with some libraries not being found. I'm going to try more methods to see if I can get it to work. 

You can always try our examples app on a physical device/simulator so if you want to see how things are looking go ahead and try that method as well 😊.

Thanks,
Alin
